### ISSUE TITLE
Design a first MVP

### ISSUE THREAD

**Issue by sgomez** [aulasoftwarelibre/cuestion-ui-kit#21]
Our first MVP should:

1. Ask for a session code
1. Check is the session code exists and:
    1. Show the active talks if the session exists
    1. Show an error if the session does not exists or something else

This need two pages:

* main page: here we ask for the session code
* session/{id} page: here we show the talks. id is the session code

Every page in next.js does not share the state between them, so we can design every page as an independent application.

The main page could have this actions:

* OPEN_SESSION_REQUEST. 
    payload: session id
    description: this action was dispatched when user send a session code
    effects: send a request to the API to search the session code
* OPEN_SESSION_SUCCESS:
    payload: session
    description: this action was dispatched if session exists (from the API request)
    effects: change the route to session page
* OPEN_SESSION_FAILURE: 
    payload: error, error description
    description : this action was dispatched if session does not exists (from the API request)
    effects: launch OPEN_ERROR_SNACKBAR

**updated with @victormonserrat suggestions:**

* OPEN_ERROR_SNACKBACK:
  payload: message
  description: show an error in a snackbar
  effects: change this status variables: error to true and errorMessage. Launch a timeout to close snackback
* CLOSE_ERROR_SNACKBACK
  payload: none
  description: close the snackbar
  effects: change error to false and errorMessage to undefined

probably we need a SNACKBAR_MESSAGE_CLOSE with a timeout

so, our state could have this values:
* session?: Session
* error: boolean
* errorMessage: Error

**Comment by sgomez** [comment]
cc @victormonserrat

**Comment by victormonserrat** [comment]
Cool! :ok_hand:

**Comment by victormonserrat** [comment]
Cool! :ok_hand: Just to say something: OPEN_SESSION_FAILURE's saga could throw a SNACKBAR_MESSAGE_OPEN action with error_description as payload and set the timeout to throw the SNACKBAR_MESSAGE_CLOSE action :nerd_face:
